# Generated by Django 2.2.10 on 2021-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=80)),
                ('details', models.TextField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
