# Generated by Django 2.2.10 on 2021-02-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='title',
            new_name='name',
        ),
    ]
