# Generated by Django 2.2.10 on 2021-02-13 07:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0002_auto_20210212_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
