# Generated by Django 2.2.10 on 2021-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0003_auto_20210213_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
